"""Updated tables

Revision ID: b45ba18cf413
Revises: 45fb8f5b9f15
Create Date: 2024-05-30 23:52:40.811244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45ba18cf413'
down_revision: Union[str, None] = '45fb8f5b9f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Car', sa.Column('id_carrier', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Car', 'Carrier', ['id_carrier'], ['id'])
    op.add_column('Driver', sa.Column('id_carrier', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Driver', 'Carrier', ['id_carrier'], ['id'])
    op.add_column('Order', sa.Column('id_driver', sa.Integer(), nullable=False))
    op.add_column('Order', sa.Column('id_car', sa.Integer(), nullable=False))
    op.add_column('Order', sa.Column('id_customer', sa.Integer(), nullable=False))
    op.drop_constraint('Order_driver_id_fkey', 'Order', type_='foreignkey')
    op.drop_constraint('Order_car_id_fkey', 'Order', type_='foreignkey')
    op.create_foreign_key(None, 'Order', 'Customer', ['id_customer'], ['id'])
    op.create_foreign_key(None, 'Order', 'Driver', ['id_driver'], ['id'])
    op.create_foreign_key(None, 'Order', 'Car', ['id_car'], ['id'])
    op.drop_column('Order', 'driver_id')
    op.drop_column('Order', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Order', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.create_foreign_key('Order_car_id_fkey', 'Order', 'Car', ['car_id'], ['id'])
    op.create_foreign_key('Order_driver_id_fkey', 'Order', 'Driver', ['driver_id'], ['id'])
    op.drop_column('Order', 'id_customer')
    op.drop_column('Order', 'id_car')
    op.drop_column('Order', 'id_driver')
    op.drop_constraint(None, 'Driver', type_='foreignkey')
    op.drop_column('Driver', 'id_carrier')
    op.drop_constraint(None, 'Car', type_='foreignkey')
    op.drop_column('Car', 'id_carrier')
    # ### end Alembic commands ###
